image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: ignore
  - port: 3035
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  - port: 9200
    onOpen: ignore
  - port: 9300
    onOpen: ignore

tasks:
  - name: MangaDex Server
    before: |
      redis-server &
    init: |
      gem install bundler && sleep 15s && script/setup
    command: |
      gem install bundler && sleep 15s && script/update && script/server
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
# add a check to pull requests (defaults to true)
    addCheck: true

vscode:
  extensions:
    - rebornix.ruby@0.28.0:6jqvDzl/avsj94yYXFjzQw==
    - wingrunr21.vscode-ruby@0.27.0:beIqQUhLRuJ5Vao4B2Lyng==
