#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f ".ruby-version" ]; then
  echo "==> Installing Bundler…"
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle config set --local path 'vendor/gems'
  bundle config set --local without 'production'
  bundle check >/dev/null 2>&1  || {
    bundle install --quiet
  }
fi

if [ -f "package.json" ]; then
  echo "==> Installing NPM packages…"
  bin/yarn install --silent
else
  echo "ERROR: MangaDex requires Yarn for managing JS dependencies."
fi


echo "==> Installing Foreman…"
gem install foreman --silent
